Adaptation for joomla_4.0
exstreme/Jcomments-Recaptcha2 pull request #35
Opened 2021-03-20 08:37 UTC by JLTRY

All changes are compatible with joomla_3 . They are encapsulated with an if JVERSION. Tested on joomla 4.0.beta 7

2021-03-20 08:51 UTC, Globulopolis commented on administrator/models/comments.php
> -				$escaped = $this->_db->Quote('%' . $this->_db->escape(JString::substr($search, 5), true) . '%');
Using substr() will cause unpredictable results with multi-byte chars. Instead of removing JString, change it to StringHelper::substr() via import or qualifier.

2021-03-20 08:52 UTC, Globulopolis commented on administrator/models/comments.php
> -				$escaped = $this->_db->Quote('%' . $this->_db->escape(JString::substr($search, 7), true) . '%');
Same as suggested above.

2021-03-20 08:52 UTC, Globulopolis commented on administrator/models/modelform.php
> +use Joomla\Utilities\ArrayHelper;
Import for what?

2021-03-20 08:53 UTC, Globulopolis commented on administrator/models/modelform.php
> +			$item = JArrayHelper::toObject($properties, 'JObject');
If you import ArrayHelper above, when use it below.

2021-03-20 08:56 UTC, Globulopolis commented on administrator/views/comments/tmpl/default.php
> +						$title = substr($title, 0, 200);
Will cause error with multi-byte.

2021-03-20 08:58 UTC, Globulopolis commented on plugins/search/jcomments.php
> +		$text = strtolower(trim($text));
Change to StringHelper::strtolower()

2021-03-20 09:00 UTC, Globulopolis commented on plugins/system/jcomments.php
> +				if (version_compare(JVERSION, '4.0', 'lt')){
These changes have any effect? getBody() in Factory available since 1.7.3 platform version.

2021-03-20 11:17 UTC, exstreme commented
Hello, can you remove logging and replace substr() on  [](https://www.php.net/manual/en/function.mb-substr.php)

2021-03-20 16:19 UTC, JLTRY commented on administrator/models/comments.php
> -				$escaped = $this->_db->Quote('%' . $this->_db->escape(JString::substr($search, 5), true) . '%');
done in last commit

2021-03-20 16:19 UTC, JLTRY commented on administrator/models/comments.php
> -				$escaped = $this->_db->Quote('%' . $this->_db->escape(JString::substr($search, 7), true) . '%');
done in last commit

2021-03-20 16:38 UTC, JLTRY reviewed
see my last changes

2021-03-20 16:38 UTC, JLTRY commented on administrator/models/modelform.php
> +use Joomla\Utilities\ArrayHelper;
look at the full file ArrayHElper is used
for instance line 34
if (version_compare(JVERSION, '4.0', '<')){
			$item = JArrayHelper::toObject($properties, 'JObject');
		} else {
			$item = ArrayHelper::toObject($properties, 'JObject');
		}

I think gihub has forgotten this modifications

2021-03-20 16:38 UTC, JLTRY commented on administrator/models/modelform.php
> +			$item = JArrayHelper::toObject($properties, 'JObject');
See full file

2021-03-20 16:48 UTC, Globulopolis commented on plugins/system/jcomments.php
> +				//$type = $app->input->post('type', '', 'post');
This will throw undefined variable in if() below.

2021-03-20 16:49 UTC, Globulopolis commented on site/classes/security.php
> +			$str = trim(strtolower($str));
Use StringHelper

2021-03-20 16:50 UTC, Globulopolis commented on site/classes/security.php
> +			$email = strtolower($email);
Use StringHelper

2021-03-20 16:50 UTC, Globulopolis commented on site/classes/security.php
> +			$name = strtolower($name);
Use StringHelper

2021-03-20 16:50 UTC, Globulopolis commented on site/classes/security.php
> +			$names = strtolower(preg_replace("#,+#u", ',', preg_replace("#[\n|\r]+#u", ',', $names)));
Use StringHelper

2021-03-20 16:50 UTC, Globulopolis commented on site/classes/text.php
> +			$str = substr($str, JCommentsText::strlen($matches[0]));
Use StringHelper

2021-03-20 16:50 UTC, Globulopolis commented on site/classes/text.php
> +		return substr($text, 0, $length);
Use StringHelper

2021-03-20 16:51 UTC, Globulopolis commented on site/classes/text.php
>  }
Please consider an empty line at the end of file.

2021-03-20 16:53 UTC, Globulopolis commented on site/helpers/system.php
>  }
Please add an empty line at the end.

2021-03-20 16:54 UTC, Globulopolis commented on site/jcomments.ajax.php
> +function my_log($msg)
Remove debug logging from this file.

2021-03-20 16:55 UTC, Globulopolis commented on site/jcomments.php
> +use Joomla\CMS\Log\Log;
Remove logging from this file.

2021-03-20 16:56 UTC, Globulopolis requested changes
@JLTRY please make changes. Remove logging and add StringHelper.

2021-03-20 20:48 UTC, JLTRY commented on plugins/system/jcomments.php
> +				//$type = $app->input->post('type', '', 'post');
I do not know how to adapt code for joomla_4 if you have a better idea
I put back the line for joomla > 4.0

2021-03-20 20:49 UTC, JLTRY commented
comments taken into account in last commit

2021-03-20 21:17 UTC, Globulopolis approved these changes
LGTM, thanks for changes.

2021-03-20 21:20 UTC, Globulopolis approved these changes

2021-04-01 06:53 UTC, JLTRY commented
Globulopolis approved this change . Why not to merge them ?

2021-04-01 08:19 UTC, merged